sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y texlive-fonts-recommended texlive-latex-extra
  texlive-fonts-extra dvipng texlive-latex-recommended latex-xcolor pgf texlive-pictures
  texlive-full
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build src/cv.tex
deploy:
  provider: releases
  api_key:
    secure: "jizXBpxcqNgWH63HNdO8JJJUCMqqqVvRvsDDRkXaNy/+fAXbUZFvhTYYNFyLntnavPUx5iztJ/6l97tfY01u+0ARWnkHrfLhsVuwFZVlKCjCwhah0KNtG4fJnDDVdepalOmPwvxLFczqhrRjJmmrp3pNt659COCWrkMfUd9Fk+F3OlWz05/3wgslorpjVt/2p45vg8oB+Otnnmn8D8f/Sn4ZzSpU71ir/edxWqdvH0sGhoP6OYpRwJFfu19hvvcHlGrdYKPmFoAGAXWjpBZyErctbV/xgOlavanz/JJ+1Dcp6yju/PvTOf+6oYjY5O8Drejankr14k/gznX4O4WoKmTSj7sBv+7mR+ctr2mqw0vOdAOqLvbmj901HGqcKkLtxZcSAvnm5WCg6TTtZWMW+bQikFUYbs9zTZ9K0Y5hrIeNBqe4WNEvjIRsn+xi25Y3rF9tt+rMCoNoD99UFATIxCH63M/KxbFN9C3yNHqaafOPrHhNnoHijfjcci4rj+2uG+98Rw5eIJi0SDJgtuDpxQm7+ZG8YBpnsca2UlcNf6O3jL7Lb7Dz7Gm6CqCmE9NGKPWKA7ksRYpa84Pmf5X4m8y8PasUbmdxFUvmA+WC85RESRWtuRSw0wqFkfdzhOGzoFwnD01SQGh97CE3lVYZYQSWNQQitrJh0dPIe461rbA="  
  file: _build/cv.pdf
  skip_cleanup: true
  overwrite: true
  on:
    repo: egavolk/cv